Update cvim

diff --git a/cvim b/cvim
--- a/cvim
+++ b/cvim
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-[[ $# -ne 1 ]] && echo "Error! I need "a" filename!!" && exit 1
+[[ $# -ne 1 ]] && echo "Error! You need "a" filename!!" && exit 1
 
 echo -e '#include <stdio.h>\n#include <stdlib.h>\n\nint\nmain(int argc, char* argv[])' > $1
 chmod +x $1
